name: Terraform CI

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2.5.0


    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2.0.2

    - name: Terraform init
      run: |
        echo `pwd`
        echo "tfpath ${{ github.event.inputs.tfpath }}"
        echo "** Running Terraform Init**"
        terraform init
      
    - name: Terraform Plan
      run: terraform plan
  
    - name: Manual Apply
      if: steps.manual_approve.outputs['contains-apply'] == 'true'
      run: terraform apply -auto-approve

    - name: Manual Approve Destroy
      if: steps.check_workflow.outputs.workflow_status == 'success'
      run: |
        echo "To destroy the resources, comment '/destroy'"
        echo "Waiting for approval..."
        sleep 5m
    
    - name: Manual Destroy
      if: steps.manual_approve.outputs['contains-destroy'] == 'true'
      run: terraform destroy -auto-approve